### ISSUE TITLE
`publish:package` task fails when multiple `zarf-package-*.tar.zst` files exist

### ISSUE THREAD

**Issue by marshall007** [defenseunicorns/uds-common#178]
Modifications needed to be made in https://github.com/defenseunicorns/uds-package-mattermost/pull/99 to handle the case where multiple packages are being built/published in the same project. In other words, you should be able to call `create:package` multiple times and then have some way to call `publish:package` for each package that is built (or once for all of them?).

For example:

```yaml
  - name: publish-packages
    description: Build packages
    actions:
      - task: create:package # creates `zarf-package-mattermost-amd64-9.9.1-uds.0.tar.zst`
      - task: create:package # creates `zarf-package-mattermost-plugins-amd64-9.9.1-uds.0.tar.zst`
        with:
          path: ./plugins
          options: "--flavor ''"
      - task: publish:package # publishes all packages named `zarf-package-mattermost-*.tar.zst`
        with:
          filter: mattermost-*
```
