### ISSUE TITLE
Unable to set callable test options from GitHub repository secret

### ISSUE THREAD

**Issue by JeffResc** [defenseunicorns/uds-common#333]
I am unable to set a Zarf variable from a GitHub repository secret, which would be helpful for loading in secrets such as license keys. Unfortunately, GitHub does not have a way to use a secret as part of a workflow input resulting in this limitation.

Some sort of workaround for this would be helpful for packages that require a secret in order to be tested.

For example:
```yaml
validate:
  needs: check-flavor
  strategy:
    fail-fast: false
    matrix:
      type: [install, upgrade]
      flavor: [upstream, unicorn, registry1]
    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@d59b1c601730bfa7ab76439643242358e529603e  # v1.2.2
    with:
      runsOn: ubuntu-latest
      upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
      options: "--set EXAMPLE_LICENSE_KEY=${{secrets.EXAMPLE_LICENSE_KEY}}"
    secrets: inherit # Inherits all secrets from the parent workflow.
```

Resulting error:
```
The workflow is not valid. .github/workflows/test.yaml (Line: 65, Col: 16): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.EXAMPLE_LICENSE_KEY
```

**Comment by Racer159** [comment]
Does this work for you?

```
setup:
  runs-on: ubuntu-latest
  outputs:
    license: ${{ steps.set-license.outputs.license }}
  steps:
    - name: set license information
      id: set-license
      run: |    
        echo "::set-output name=license::${{ secrets.EXAMPLE_LICENSE_KEY }}"
validate:
  needs: check-flavor
  strategy:
    fail-fast: false
    matrix:
      type: [install, upgrade]
      flavor: [upstream, unicorn, registry1]
    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@d59b1c601730bfa7ab76439643242358e529603e  # v1.2.2
    with:
      runsOn: ubuntu-latest
      upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
      options: "--set EXAMPLE_LICENSE_KEY=${{ needs.setup.outputs.license }}"
    secrets: inherit # Inherits all secrets from the parent workflow.
```
