### ISSUE TITLE
Upgrade tests fail when removing dependencies from test bundle

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-common#374]
If the latest release of a uds-package includes bundle dependencies that have been removed in PR, the upgrade tests fail because of those dependencies being missing. See this failed upgrade test for an example: https://github.com/defenseunicorns/uds-package-activepieces/actions/runs/12694188909/job/35383434826?pr=2

The example run failed after removing everything from the src directory and getting rid of all the dependency related tasks in the repo.

As a developer, when dependencies are removed from a bundle, I expect the previous release to still build and deploy successfully in the upgrade tests.

**Comment by zachariahmiller** [comment]
@jacobbmay Currently the way to handle this is to remove the dependencies and keep this or something similar until the next release when its no longer required by the previous bundle the upgrade is deployed off of:

```yaml
  - name: test-upgrade
    description: Test an upgrade from the latest released package to the current branch
    actions:
      - task: upgrade:create-latest-tag-bundle
        with:
          dep_commands: "./uds run dependencies:create"
```

See mattermost as an [example](https://github.com/defenseunicorns/uds-package-mattermost/blob/b3609ea7ebd893e3b0cde81db805c2076d407ab5/tasks.yaml#L66)

I understand this is less than ideal, but we have to mitigate whatever the previous tags deployment required.
