### ISSUE TITLE
Update lint task to work locally as well as in CI irrespective of pip vs pip3

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-common#55]
Update lint task to work locally as well as in CI irrespective of pip vs pip3. Working example from postgres operator:

```
tasks:
  - name: check
    description: "Run linting checks"
    actions:
      - description: install yamllint deps
        cmd: CMD=pip && which $CMD || CMD=pip3 && $CMD install yamllint
      - description: yaml lint
        cmd: yamllint . -c .yamllint --no-warnings
```
